### ISSUE TITLE
[Bego Ripoll]

### ISSUE THREAD

**Issue by bripollc** [Ironhack-data-bcn-april-2023/project-II-pipelines#1]
https://github.com/bripollc/02_scrapping-apis

**Comment by ta-data-bcn** [comment]
Bueeeenas Bego! 🚀🚀


Antes de todo, vaya proyectazo!!!!!!!!!!! Se nota mucho desde el primer momento lo currado que está y el tema también super original e interesante!!!
Un poco de feedback:


**Respecto a la organización del repositorio** 📚

- El gitignore está bien. Sólo se te coló un .DS_Store que en realidad no suma nada al  repo, también lo podrías ignorar. También muy bien hecho al ignorar tus conversaciones privadas!!
- Aparte de eso, la organización del repo está perfecta. Todo en sus respectivas carpetas dejando solo el main a la vista!! 
- Yo te recomiendo dejar un notebook de jupyter también (ipynb), ya que es más visual y dejar el procedimiento que has hecho para llegar hasta ahí. En una carpeta que se llame notebooks, creo que también es chulo ver cómo has trabajado y qué pasos has tomado.

**El README.md** 📖

- Me gusta que tu readme sea tan claro en qué pasos has tomado y con qué intenciones. 
- Los workflows que hiciste en tu último proyecto y en este están super bien!!! 
- Me falta un poco que expliques cuáles han sido las conclusiones de tu trabajo, en el apartado de conclusiones has puesto más los next steps que las conclusiones, entonces me quedo un poco sin saber qué cosas has sacado de tu project. Igual si agregas alguna gráfica aquí también te puede quedar bien. Y sobretodo explicar qué han dicho tus gráficas, si tus hipótesis han sido confirmadas o no etc. 

**El código** 👩‍💻

- El código está perfecto, todo en sus funciones, los comentarios que van describiendo los datos que usas etc. Igual algún docstring que explique lo que hace la función en general sería bueno aquí.
- Cómo he dicho antes igual sería chulo dejar tu notebook para ver más claramente cuál ha sido tu trayecto hasta llegar aquí!

**Visualización** 🎨

- La visualización está bien, plotly es mucho más agradable a la vista que seaborn o matplotlib. 
- Igual me falta un poco alguna gráfica más especializada, como por ejemplo una de correlaciones. 


En general como ya he dicho es un proyectazo Bego!!! El propósito era juntar dos bases de datos extraídas de diferentes maneras y hacer un análisis, y lo has hecho muy bien, así que muuuchas felicidades y ánimo para el siguiente.
