### ISSUE TITLE
Project 2 Ramses

### ISSUE THREAD

**Issue by RamsesMR5** [Ironhack-data-bcn-april-2023/project-II-pipelines#10]
https://github.com/RamsesMR5/Project-2-Ramses

**Comment by ta-data-bcn** [comment]
Holaa Ramses! 🚀
Muchas felicidades por tu proyecto!
Un poco de feedback:


Respecto a la organización del repositorio 
- Está bien organizado, en carpetas y luego un notebook principal!!


El README.md 
- NO EXISTEEEEE
- Intenta explicar siempre tu proyecto en el readme, sino es muy difícil descifrar lo que has hecho en tu trabajo, lo que has querido analizar, tus hipótesis, conclusiones, etc. 


El código 
- Está bien, has sacado bien las cosas de la API de spotify que no es facil. 
- Se que estuviste mucho tiempo trabajando en eso y que perdiste mucho tiempo intentando sacar las cosas de la API.
- Al final el trabajo consistía en sacar info de una api/web-scraping y juntar esa data con un csv preexistente para enriquecer su información. 
- Entonces entiendo que del csv has sacado los artistas y de la api has añadido cuantas semanas ha estado on top? Pero esto ya te lo ponía en el csv inicial entonces no sé como has enriquecido tu data con la API


Visualización 
- Las visualizaciones están bien!
- Me gustaría ver un gráfico donde vea a todos, igual agrupado por artistas o ver qué canciones han sido las que más tiempo han estado on top.


En general buen trabajo Ram, pero te falta el paso de relacionar una tabla con la otra. 
Hiciste lo que se pedía que era hacer un scraping o API, y coger un dataset, pero te faltó relacionar una cosa con la otra!
