### ISSUE TITLE
Project 2

### ISSUE THREAD

**Issue by jomape-iron** [Ironhack-data-bcn-april-2023/project-II-pipelines#11]
https://github.com/jomape-iron/Project_2.git

Tengo que "enchular" readme, hoy me pongo con ello.

**Comment by ta-data-bcn** [comment]
Holaa Jose! 🚀
Muchas felicidades por tu proyecto!
Un poco de feedback:


Respecto a la organización del repositorio 📚
- El repositorio está limpio, no tienes documentación innecesaria así que perfecto.
- Lo que me falta ver aquí son las carpetas con funciones 👀👀👀👀
- Y también faltaría la carpeta de imágenes.


El README.md  📖
- Está bien estructurado y limpio.
- Te recomiendo añadir tus gráficos en las conclusiones para demostrar mejor tus statements. También me gustaría ver una respuesta a tus hipótesis iniciales en la conclusión
- Igual aún estás en proceso de acabarlo?


El código  👩‍💻
- Dentro de que no has encapsulado ni modularizado el código está bien
- La parte de extraer lo datos, que era el objetivo del proyecto, está perfecta. Aparte usaste API y web-scrapping así que muy muy bien por usar las dos. Tu función de web-scrapping muy top.
- También has hecho correlations que muy top!! Osea perfecto Jose!!


Visualización  🎨
- Buenas gráficas de correlaciones que se explican ellas solitas así que perfecto!


En general muy buen proyecto Jose! Faltan algunos detalles como las funciones pero se ve que has trabajado bien! Felicidades.
