### ISSUE TITLE
Paula Gonzalez Project 2!

### ISSUE THREAD

**Issue by pagoba94** [Ironhack-data-bcn-april-2023/project-II-pipelines#2]
https://github.com/pagoba94/project2

**Comment by ta-data-bcn** [comment]
Bueeeenas PAULAGG! 🚀🚀


Antes de todo, felicidades por tu proyecto!!!!!!!!!!! Se nota que le has metido mucho esfuerzo y así lo demuestra este trabajazo!!!!!!! Felicidades 💪💪
Un poco de feedback:



**Respecto a la organización del repositorio** 📚

- La organización del repo está perfecta! Has ignorado todo lo que no aporta valor a tu trabajo y dejado todo lo que sí está organizado en carpetas.
- Nada que decir sobre la organización del repo porque está 👌👌👌👌


**El README.md** 📖

- El Readme también está muy bien, has añadido todo lo que hablamos en el proyecto número 1 y se entiende perfectamente de qué va tu trabajo y con qué objetivos has trabajado.
- Lo único que añadiría en el readme es entre la introducción y los resultados explicar un poco el proceso de transformación que han pasado tus datos. Simplemente las modificaciones que has hecho y cómo has mantenido lo que te importa etc.
- Súper de añadir las tablas al readme que lo hace mucho más visual. 

**El código** 👩‍💻

- El código está perfecto, todo en sus funciones, los comentarios que van describiendo los datos que usas, los docstrings que explican el funcionamiento de tus funciones…
- También me gusta que hayas dejado los notebooks, es chulo ver lo que ibas haciendo paso por paso así que te recomiendo mantener esta organización siempre!!!


**Visualización** 🎨

- La visualización está muy bien, plotly es mucho más agradable a la vista que seaborn o matplotlib, me gusta que pongas 3 variables en un gráfico como en el scatter de burbujas, muy top!!!! 
- También que ya hayas tocado mapas 👌👌👌



En general como me parece un proyectazo Paula!!!!!! Te lo estás currando mucho y se ve tu motivación por el curso. Has conseguido de largo el objetivo principal del trabajo, FELICIDADES!!!!!!
