### ISSUE TITLE
Leticia-Project_II

### ISSUE THREAD

**Issue by LeticiaIruela** [Ironhack-data-bcn-april-2023/project-II-pipelines#3]
https://github.com/LeticiaIruela/Project_II

**Comment by ta-data-bcn** [comment]
Holaa LETIII! 

Primero solo quiero felicitarte! Sé que es frustrante a veces cuando te estancas, pero cuando veo el proyecto veo las muchas horas que hay detrás así que GOOD JOB!!!!!! Es un muy buen proyecto!

Un poco de feedback:

**Respecto a la organización del repositorio** 📚
- Está super limpio, molt be!!!!!!
- Veo que te falta la carpeta de imágenes… Acaso las has arrastrado en el Readme editor ?? 😱😱 haha mejor hazte una carpeta la próxima vez para que se pueda acceder también a las imágenes y gráficos!


**El README.md** 📖
- El Readme también está muy bien, bien organizado de arriba hasta abajo y siguiendo el hilo de intro - hipótesis - metodología - visualizaciones/conclusiones!!!!!
- Está muy bien el añadir las tablas al readme que lo hace mucho más visual. 
- Yo lo pasaría por grammarly que he visto bastantes faltas de ortografía 🙃




**El código** 👩‍💻
- Está super bien que en tu notebook vayas explicando que haces en cada paso, le das mucha estructura con los títulos y luego defines lo que haces con subtítulos molt be!!!!!!!
- Te ha faltado utilizar las funciones que has definido en tu carpeta src, veo que ha habido un intento de usarlas pero seguramente ya no dabas para mas haha
- Al menos has hecho las funciones!  

**Visualización** 🎨
- La visualización está bien, plotly es mucho más agradable a la vista que seaborn o matplotlib, 
- Igual se te ha quedado un poco corto el scraping ya que solo estabas analizando 5 recetas, e igual por eso los gráficos tampoco han mostrado tanto lo que querías mostrar.

En general como muy buen proyecto Leti!!!!!! Has utilizado diferentes datos de diferentes bases así que objetivo cumplido! Felicidades
