### ISSUE TITLE
Jean Paul Bancelin

### ISSUE THREAD

**Issue by jeanpaulbr** [Ironhack-data-bcn-april-2023/project-II-pipelines#5]
https://github.com/paulbancelin/Project-2-NBA

**Comment by ta-data-bcn** [comment]
Holaa Paul! 🚀
Muchas felicidades por tu proyecto!
Un poco de feedback:

Respecto a la organización del repositorio 📚
- Está bien organizado, se te ha colado un .DS_Store que podrías ignorar dentro de tu .gitignore. 
- Aparte de esto está limpio!


El README.md 📖
- NO EXISTE
- Sin readme es muy difícil entender lo que has hecho, lo que has querido analizar, tus hipotesis, conclusiones, etc. 


El código 👩‍💻
- El código está bien también, sigues imprimiendo los dataframes enteros cosa que hace la lectura un poco difícil ya que hay que buscar donde está el código todo el rato.
- Está bien que hayas hecho web scraping y hayas utilizado un dataset, era el objetivo del proyecto
- Me falta ver como una data enriquece la otra, no has juntado una data con la otra, entonces no estás analizando algunas cosas que podrían haber sido ineteresantes.
- Por lo demás todo OK


Visualización 🎨
- Las visualizaciones están bien también, pero aquí también me falta ver si una cosa influencia la otra, podrías haber puesto el payroll y el numero de campeonatos en una misma gráfica
- También podrías mirar si los años en los que ha ganado el equipo ha tenido un budget por encima de su media o no?
- Creo que podrías haber exapandido bastante más esta parte!


En general buen trabajo Paul, pero te falta el paso de relacionar una tabla con la otra. 
Hiciste lo que se pedía que era hacer un scraping o API, y coger un dataset, pero te faltó relacionar una cosa con la otra!
