### ISSUE TITLE
SpaceXMotoPapi

### ISSUE THREAD

**Issue by pablocabadas** [Ironhack-data-bcn-april-2023/project-II-pipelines#6]
![giphy-13](https://user-images.githubusercontent.com/127872717/235608872-b79238cd-9158-4208-8d52-61b9f63f4ca3.gif)

https://github.com/pablocabadas/project-spacex.git

**Comment by ta-data-bcn** [comment]
Holaa Pablo! 🚀
Muchas felicidades por tu proyecto!
Un poco de feedback:


Respecto a la organización del repositorio 📚
- Está bien organizado, te recomiendo usar carpetas para organizar mejor tu repositorio y que sea más fácil de navegar
- De esta manera se sabe si un file es data, funciones, código o imagen!


El README.md 📖
- Muy bueno Pablo! Es interesante y explica bien tu proyecto
- Te recomiendo usar títulos y subtítulos para organizar mejor el readme en general. 
- Las imágenes no se han colgado! 


El código 👩‍💻
- Muy bien creando funciones! Te felicito!!!!!
- El resto del código está bien también, gracias por crear el main.ipynb para no tener que scrollear toda el dataframe todo el rato
- En general veo un buen improvement desde el último trabajo y espero seguir viéndolo en el siguiente! Sigue así!!


Visualización 🎨
- Las visualizaciones están bien también!!!!!
- Te recomiendo poner títulos en tus gráficos para entender mejor lo que estás mostrando


En general buen trabajo Pablo, has hecho todo lo que se pedía, has juntado dos dataframes extraídos de diferentes sources y has hecho predicciones basados en ellos!!!🚀🚀
