### ISSUE TITLE
Project2-Laura

### ISSUE THREAD

**Issue by laumosa** [Ironhack-data-bcn-april-2023/project-II-pipelines#9]

**Comment by laumosa** [comment]
https://github.com/laumosa/project2---API-scrapping

**Comment by ta-data-bcn** [comment]
Holaa Laura! 🚀
Muchas felicidades por tu proyecto!
Un poco de feedback:


**Respecto a la organización del repositorio 📚**
- Está super limpio, molt be!!!!!!
- Lo único que cambiaría sería el DS.Store que no aporta nada a tu proyecto! Añádelo en el gitignore la próxima vez antes de hacer el primer push!


**El README.md 📖**
- La organización está perfecta, con títulos, subtítulos, bulletpoints etc. hace la lectura muy visual y fácil de seguir el hilo de tu proyecto
- La próxima vez, intenta añadir tus gráficos al readme! Es lo que al final explica mejor tus hipótesis. 
- No acabo de entender del todo tus conclusiones, al no ver las gráficas también me falta aquí un poco de ayuda. Explicas que las partículas 2.5 suben al entrar en cuarentena? Como puede ser? 


**El código 👩‍💻**
- Tu código como en el último proyecto está muy bien ordenado, entiendes lo que estás haciendo te felicito porque está perfecto!!!!!!!
- Muy bien modularizado y poniendo todo en funciones.
- Podrías poner más docstrings dentro de las funciones para que se entienda mejor qué hace cada una.
- La parte de extraer lo datos, que era el objetivo del proyecto, está perfecta


**Visualización 🎨**
- Se ven todas las gráficas en blanco!!!
- Si lo has hecho con plotly hay una forma de guardarlo en formato html:
```python
import plotly.io as pio 
pio.write_html(fig, file='hello_world.html', auto_open=True)
```


En general muy buen trabajo Laura!!!!! Sigue así!!!!!!
